rancher/rancher.github.io

- _includes/rancher-sidebar.html
- rancher/concepts/index.md
- rancher/rancher-compose/index.md
- rancher/upgrading/index.md
@will-chan @alena1108 Can you review? I added sidekicks into the concept page as well as in the rancher-compose section.
> Sidekick documentation for CLI

- rancher/installing-rancher/installing-server/multi-nodes/index.md
When running in HA mode, you need to run the websocket proxy externally.
> updated to run websocket-proxy externally

- os/cloud-config/index.md
- os/running-rancheros/server/install-to-disk/index.md
- rancher/rancher-compose/rancher-services/index.md
- rancher/rancher-ui/infrastructure/hosts/index.md
@vincent99 Does this look like a good place for the security stuff?
> Updated based on security question

- rancher/installing-rancher/installing-server/multi-nodes/index.md
> Removed the setting from docs.

- rancher/faqs/troubleshooting/index.md
Minor: wrong filenames for logs.
> Hyphons not underscores

- rancher/installing-rancher/installing-server/index.md
- rancher/upgrading/index.md
Added so we can test in this next round. 
Todo:
* upgrade instructions.
> Adding in bind mount flag info

- css/rancher.css
- js/rancher.js
So you can easily copy anchor link URLs...
> Add anchor links on header hover

- rancher/installing-rancher/installing-server/basic-ssl-config/index.md
@cloudnautique Please review to see if the notes about settings is accurate.
> Added apache config for SSL

- os/cloud-config/index.md
- os/configuration/index.md
corrections to Configuration overview
> corrections to Configuration overview

- os/configuration/custom-kernels/index.md
> custom kernel

- os/rancheros-tools/ros/install/index.md
> update ros install doc

- rancher/installing-rancher/installing-server/basic-ssl-config/index.md
https://github.com/rancher/rancher/issues/2186
> Updated SSL docs to increase timeout value

- _includes/os-sidebar.html
- os/cloud-config/index.md
- os/configuration/custom-console/index.md
- os/configuration/dkms/index.md
- os/configuration/docker/index.md
- os/configuration/index.md
- os/configuration/kernel-modules-kernel-headers/index.md
- os/configuration/loading-kernel-modules/index.md
- os/index.md
- os/running-rancheros/workstation/boot-from-iso/index.md
> Updates for v0.4

- rancher/installing-rancher/installing-server/multi-nodes/index.md
@cloudnautique Can you review?
> Clarifications on websocket-proxy in HA mode

- rancher/configuration/api-keys/index.md
These are some clarifications and examples which I think will improve the docs.
I am reading the docs to learn Rancher and I added those based on what I did not immediately understand from reading and had to work out.
> Adds some small clarifications and examples.

- rancher/concepts/health-checks/index.md
- rancher/rancher-compose/rancher-services/index.md
- rancher/rancher-ui/applications/stacks/adding-services/index.md
I added some links as I had at first totally missed a good document on Health Check which was there but not immediately visible. 
I added details on the Health checks, particularly two fields which were not immediately obviously which I got [clarifications for on the forum](http://forums.rancher.com/t/health-check-not-totally-clear-on-meaning-of-unhealthy-healthy-threshold/790).
> More details for Health Checks

- _includes/os-sidebar.html
- os/faqs/index.md
https://github.com/rancher/os/issues/619
> Removed FAQs

- rancher/rancher-compose/rancher-services/index.md
- rancher/rancher-ui/applications/stacks/adding-balancers/index.md
Copy edited the content for two files for clarity and minimalism. Directly editing on GitHub pages as locally making changes and then committing insert unwanted formatting.
> Submitting a copy edit 

- rancher/faqs/troubleshooting/index.md
Noticed the typo in the command, updated wording whilst i was there to be clearer.
> Updated wording and fixed typo in command for troubleshooting

- rancher/installing-rancher/installing-server/index.md
- rancher/upgrading/index.md
Updates to the docs following comments on recent tickets and usage of them.
> Updated instructions for bind mounts, upgrading agents.

- rancher/concepts/index.md
Used technical writing conventions/style
> Updated Concepts Section for clarity

- rancher/configuration/access-control/index.md
Performed doc testing. Configured GitHub.
Reviewed and edited doc for clarity and conformity. Followed technical writing conventions.
> Access Control Page Has Been Reviewed

- rancher/rancher-ui/applications/stacks/index.md
- rancher/rancher-ui/infrastructure/hosts/custom/index.md
While doc testing, reviewed and edited the doc for clarity. Fixed typos and followed conventions and conformity (eg: docker vs Docker).
> Reviewed Adding Custom Hosts

- os/configuration/setting-up-docker-tls/index.md
- os/rancheros-tools/ros/tls/index.md
> RancherOS TLS configuration

- os/running-rancheros/workstation/docker-machine/index.md
- rancher/api/index.md
- rancher/concepts/health-checks/index.md
- rancher/concepts/index.md
- rancher/concepts/scheduling/index.md
- rancher/faqs/containers/index.md
- rancher/faqs/index.md
- rancher/faqs/troubleshooting/index.md
- rancher/installing-rancher/installing-server/multi-nodes/index.md
- rancher/rancher-compose/scheduling/index.md
- rancher/rancher-ui/applications/stacks/adding-balancers/index.md
- rancher/rancher-ui/infrastructure/containers/index.md
- rancher/rancher-ui/infrastructure/hosts/custom/index.md
- rancher/rancher-ui/infrastructure/hosts/other/index.md
Not trying to be 'that guy', just trying to help out.
> Documentation - Correcting a few minor spelling mistakes

- os/running-rancheros/cloud/gce/index.md
Fixed Broken Link reported by Broken link #169
> Fixed Broken Link reported by Broken link #169

- rancher/installing-rancher/installing-server/basic-ssl-config/self-signed-certs/index.md
First pass docs for running a self signed SSL certificate on Rancher
Server.
Do not merge until all PRs have been merged.
> Add docs for self signed certs

- rancher/api/api-resources/serviceUpgrade/index.md
https://github.com/rancher/rancher/issues/3134
> Updated serviceUpgrade page

- _includes/rancher-sidebar.html
- rancher/configuration/settings/index.md
- rancher/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/installing-rancher/installing-server/index.md
- rancher/installing-rancher/installing-server/no-internet-access/index.md
- rancher/rancher-ui/applications/stacks/adding-services/index.md
- rancher/rancher-ui/infrastructure/hosts/other/index.md
@cloudnautique Could you review the SSL configuration section?
> Updated installing docs

- _includes/rancher-sidebar.html
- _layouts/rancher-default.html
- rancher/catalog/index.md
- rancher/configuration/environments/index.md
- rancher/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/installing-rancher/installing-server/index.md
- rancher/kubernetes/index.md
- rancher/metadata-service/index.md
- rancher/rancher-compose/commands/index.md
- rancher/rancher-ui/applications/catalog/index.md
@LLParse Would you be able to review for me?
> Kubernetes Docs

- rancher/concepts/index.md
to match the other "access control" link on the page ;-)
> Lowercase "access control"

- rancher/labels/index.md
- rancher/rancher-compose/index.md
Following feedback from my team, just some small tweaks to make it easier to understand.
> Tweaks to linking documentation to make it a little clearer

- rancher/latest/en/configuration/access-control/index.md
Not sure if this is being helpful or pedantic!
> Minor change to Access Control section

- rancher/latest/en/catalog/index.md
the indentation was causing github to not see the block as yaml code
> Fix code block being incorrectly formatted

- os/running-rancheros/server/pxe/index.md
https://github.com/rancher/os/issues/965
> Update iPXE script example

- rancher/latest/en/configuration/environments/index.md
Several minor corrections for missing or additional words in addition to some rephrasing.
> Environments corrections

- _includes/rancher-sidebar.html
- rancher/latest/en/configuration/machine-drivers/index.md
- rancher/latest/en/configuration/settings/index.md
- rancher/latest/en/kubernetes/index.md
- rancher/latest/en/kubernetes/ingress/index.md
- rancher/latest/en/rancher-ui/infrastructure/certificates/index.md
- rancher/latest/en/rancher-ui/infrastructure/hosts/other/index.md
- rancher/latest/zh/kubernetes/index.md
- rancher/latest/zh/rancher-ui/infrastructure/hosts/other/index.md
- rancher/v1.0/en/configuration/settings/index.md
- rancher/v1.0/zh/configuration/settings/index.md
@alena1108 Can you review the k8s ingress changes?
> Updated machine drivers and added ingress options

- rancher/latest/en/api/index.md
just a small fix for better readability
> fixed inline code block in `scoping.2`

- os/configuration/storage/index.md
> Update ZFS configuration docs

- os/configuration/custom-kernels/index.md
Update custom kernel doc: kernel tarball format
> Update custom kernel doc: kernel tarball format

- os/configuration/setting-up-docker-tls/index.md
> Update TLS configuration doc

- os/configuration/storage/index.md
> Custom storage for docker

- os/configuration/networking/index.md
> NIC bonding

- os/configuration/custom-rancheros-iso/index.md
> Building GCE tarball

- README.md
* Syntax cleanup
* Add mention to `jekyll serve`
* Fix some typos
> Clean README up

- rancher/latest/en/catalog/private-catalog/index.md
fixes `mapping values are not allowed in this context` yaml syntax error
> Adds colon to catalog section

- rancher/latest/en/api/api-resources/environment/index.md
* Add fields details
* Syntax cleanup
> More environment details

- os/cloud-config/index.md
Thanks @joshwget for the wording!
> Updated notes on services in cloud config files

- os/configuration/start.md
RancherOS configuration application order
> RancherOS configuration application order

- rancher/latest/en/hosts/index.md
Move `Ability to communicate...` to next line
> Bad carriage return

- os/storage/using-zfs/index.md
> Update ZFS install process

- os/running-rancheros/server/install-to-disk/index.md
Fixed a tiny spelling mistake.
> Spelling mistake fixed in index.md

- os/running-rancheros/server/pxe/index.md
The previous version of the iPXE script did not work.
> Improve PXE documentation

- os/contributing/index.md
> Update some RancherOS build info

- os/configuration/setting-up-docker-tls/index.md
- os/contributing/index.md
> Add a little RancherOS dev info to docs

- os/running-rancheros/workstation/docker-machine/index.md
Adding System Services went to 404 fixed to go to correct page
> Fixed error in OS Docker Machine link

- os/configuration/running-commands/index.md
> Document putting 'docker run' commands in /etc/rc.local

- os/configuration/docker/index.md
> Update Docker configuration docs

- os/configuration/custom-kernels/index.md
- os/configuration/users/index.md
- os/running-rancheros/cloud/aws/index.md
- os/running-rancheros/server/pxe/index.md
Some things I noticed while building a custom kernel
> Small dev docs additions

- os/upgrading/index.md
it is not possible to upgrade a docker-machine based installation.
> added note that upgrading docker-machine VMs

- rancher/v1.2/en/cli/commands/index.md
was going to hosts and not logs
> Fix incorrect Link for Logs Reference

- os/amazon-ecs/index.md
> London AMI

- rancher/v1.2/en/cattle/rancher-compose/index.md
`docker.compose.yml` => `docker-compose.yml`
> Fix filename reference

- os/running-rancheros/server/raspberry-pi/index.md
I see questions around this in IRC all the time, so it must be a source of confusion.
> Add note about Raspberry Pi installs

- rancher/v1.2/en/hosts/amazon/index.md
- rancher/v1.2/en/hosts/custom/index.md
- rancher/v1.2/en/hosts/exoscale/index.md
- rancher/v1.2/zh/hosts/amazon/index.md
- rancher/v1.2/zh/hosts/custom/index.md
- rancher/v1.2/zh/hosts/exoscale/index.md
- rancher/v1.3/en/hosts/amazon/index.md
- rancher/v1.3/en/hosts/custom/index.md
- rancher/v1.3/en/hosts/exoscale/index.md
- rancher/v1.3/zh/hosts/amazon/index.md
- rancher/v1.3/zh/hosts/custom/index.md
- rancher/v1.3/zh/hosts/exoscale/index.md
> Added notes on ports based on networking type

- rancher/v1.3/en/cattle/rancher-compose/index.md
Section: [SETTING UP RANCHER COMPOSE WITH RANCHER SERVER](https://docs.rancher.com/rancher/v1.3/en/cattle/rancher-compose/#setting-up-rancher-compose-with-rancher-server)
> fix(link): fix deadlink in ranger-compose

- rancher/v1.4/en/kubernetes/ingress/index.md
> add steps for creating LBs for particular hosts/global

- rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/index.md
> add spdy protocol to nginx for SSL

- rancher/v1.4/en/cattle/webhook-service/index.md
> Webhook-service docs

- _includes/rancher-sidebar-v1.4.html
- rancher/v1.4/en/kubernetes/addons/index.md
> add docs for helm

- os/configuration/docker/index.md
- os/configuration/index.md
- os/configuration/kernel-modules-kernel-headers/index.md
- os/configuration/loading-kernel-modules/index.md
- os/configuration/running-commands/index.md
- os/configuration/switching-consoles/index.md
- os/contributing/index.md
- os/storage/using-zfs/index.md
- os/system-services/adding-system-services/index.md
> RancherOS v0.8.0 docs changes

- os/amazon-ecs/index.md
> ECS AMI's for 0.8.0

- _includes/os-sidebar.html
- os/amazon-ecs/index.md
- os/security/index.md
> v0.8.1 release and security page

- rancher/v1.4/en/kubernetes/persistent-storage/index.md
Adding documentation for NFS/EBS pv on kubernetes.
> Add persistent storage docs for k8s

- rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/index.md
Added headers for HAProxy SSL offloading
> Add SSL headers for HAProxy

- os/amazon-ecs/index.md
- os/running-rancheros/server/pxe/index.md
- os/upgrading/index.md
> v0.9.0 docs changes

- rancher/v1.5/en/swarm/index.md
Adding information that is in the catalog README but not in the user docs.
> Update Swarm Doc

- rancher/v1.5/en/quick-start-guide/index.md
> Rancher CLI: update docs to use rancher config

- rancher/v1.5/en/kubernetes/index.md
> Kubernetes Doc: Removed Rancher UI

- rancher/v1.2/en/cli/commands/index.md
- rancher/v1.3/en/cli/commands/index.md
- rancher/v1.4/en/cli/commands/index.md
- rancher/v1.5/en/cli/commands/index.md
- rancher/v1.6/en/cli/commands/index.md
Update couple of help messages to matching subcommand name.
> Fixed subcommand mismatch for help messages.

- os/amazon-ecs/index.md
- os/running-rancheros/cloud/gce/index.md
- os/security/index.md
- os/storage/using-zfs/index.md
> RancherOS release note updates

- rancher/v1.5/en/kubernetes/upgrading/index.md
- rancher/v1.6/en/kubernetes/upgrading/index.md
https://github.com/rancher/rancher/issues/8036
> notes about how to keep etcd labels during k8s upgrade

- rancher/v1.6/en/installing-rancher/installing-server/index.md
Reverts rancher/rancher.github.io#780
> Revert "Remove redirect on installing Rancher page"

- rancher/v1.1/en/hosts/amazon/index.md
- rancher/v1.2/en/hosts/amazon/index.md
- rancher/v1.3/en/hosts/amazon/index.md
- rancher/v1.4/en/hosts/amazon/index.md
- rancher/v1.5/en/hosts/amazon/index.md
- rancher/v1.6/en/hosts/amazon/index.md
Supersedes https://github.com/rancher/rancher.github.io/pull/730
> Add instructions when using custom AMI

- rancher/v1.0/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.1/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/index.md
Supersedes https://github.com/rancher/rancher.github.io/pull/506
> Only set Upgrade header in nginx when it's already present

- rancher/v1.0/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.1/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/index.md
- rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/index.md
Supersedes https://github.com/rancher/rancher.github.io/pull/428/files
> Add Apache module for websocket protocol when using proxy

- _includes/os-sidebar.html
- os/amazon-ecs/index.md
- os/configuration/docker/index.md
> v1.0.3 release

- rancher/v1.6/en/index.md
Reverts rancher/rancher.github.io#819
> Revert "Update index.md"

- rancher/v1.6/en/kubernetes/rbac/index.md
> Document RBAC role for listing namespaces

- rancher/v1.6/en/cli/variable-interpolation/index.md
usage description for {{ .Stack.Name }}
> add .Stack.Name doc

- rancher/v1.6/en/cattle/secrets/index.md
Follow-up on https://github.com/rancher/rancher.github.io/pull/794
> Secrets are available in compose file version 2

- rancher/v1.2/en/hosts/azure/index.md
- rancher/v1.3/en/hosts/azure/index.md
- rancher/v1.4/en/hosts/azure/index.md
- rancher/v1.5/en/hosts/azure/index.md
- rancher/v1.6/en/hosts/azure/index.md
https://github.com/rancher/rancher/issues/9541
> Corrected instructions on adding Azure hosts through machine integration

- rancher/v1.6/en/faqs/agents/index.md
- rancher/v1.6/en/faqs/server/index.md
https://github.com/rancher/rancher/issues/9224
> Fix redirects for FAQ server/agents

- rancher/v1.6/en/kubernetes/private-registry/index.md
from `to point a private registry for being able to installing` to `to point to a private registry for installing`
> modified grammar

- rancher/v1.6/en/kubernetes/private-registry/index.md
From `uses an image whose network/ipc namespaces in each pod will use.` to `uses an image whose network/ipc namespaces will be used in each pod.`
> updated pod infra section

- rancher/v1.6/en/catalog/private-catalog/index.md
https://github.com/rancher/rancher/issues/9570
> range >= parsing issue

- rancher/v1.6/en/catalog/private-catalog/index.md
Reverts rancher/rancher.github.io#860
> Revert "range >= parsing issue"

- rancher/v1.6/en/catalog/private-catalog/index.md
https://github.com/rancher/rancher/issues/9570
> add quotes around upgrade_from values

- os/amazon-ecs/index.md
- os/configuration/resizing-device-partition/index.md
- os/running-rancheros/server/install-to-disk/index.md
- os/running-rancheros/server/pxe/index.md
- os/storage/additional-mounts/index.md
- os/storage/state-partition/index.md
- os/storage/using-zfs/index.md
- os/system-services/custom-system-services/index.md
> RancherOS v1.0.4

- os/v1.0/en/index.md
Just a typo and update URL to Docker Engine user guide
> Typo and Docker link fix

- _includes/rancher-sidebar-v1.6.html
- rancher/v1.6/en/installing-rancher/installing-server/index.md
Addresses issue https://github.com/rancher/rancher/issues/4199
> added doc for mysql over ssl

- rancher/v1.6/en/installing-rancher/installing-server/index.md
added note about support in Rancher 1.6.3+
> added note about support in Rancher 1.6.3+

- rancher/v1.6/en/kubernetes/backups/index.md
From a fresh set of eyes, it was confusing. This has more deliberate steps etc.
> Updated to make this easier to follow

- os/v1.0/en/running-rancheros/server/install-to-disk/index.md
> Fix installation cloud-config final path

- rancher/v1.6/en/upgrading/index.md
> Broken link

- rancher/v2.0/en/faq/index.md
Infinite self redirect is removed.
> remove redirect to self

- rancher/v1.2/en/installing-rancher/installing-server/index.md
- rancher/v1.3/en/installing-rancher/installing-server/index.md
- rancher/v1.4/en/installing-rancher/installing-server/index.md
- rancher/v1.5/en/installing-rancher/installing-server/index.md
- rancher/v1.6/en/installing-rancher/installing-server/index.md
https://github.com/rancher/rancher/issues/10140
> Add docs on --advertise-address

- rancher/v1.2/en/faqs/agents/index.md
- rancher/v1.3/en/faqs/agents/index.md
- rancher/v1.4/en/faqs/agents/index.md
- rancher/v1.5/en/faqs/agents/index.md
- rancher/v1.6/en/faqs/agents/index.md
https://github.com/rancher/rancher/issues/9387
> Correct details on running the rancher/agent container

- rancher/v1.5/en/kubernetes/index.md
- rancher/v1.6/en/kubernetes/index.md
https://github.com/rancher/rancher/issues/10273
> More explanation on kubectl config generation

- _includes/rancher-sidebar-v1.6.html
- rancher/v1.6/en/installing-rancher/installing-server/no-internet-access/index.md
https://github.com/rancher/rancher/issues/10246
> Add airgap catalog info

- rancher/v1.6/en/cattle/adding-load-balancers/index.md
> Docs for haproxy drain feature - Available as of Rancher v1.6.11

- rancher/v1.6/en/installing-rancher/installing-server/index.md
https://github.com/rancher/rancher/issues/9329
> Docs on --db-strict-enforcing - Available as of Rancher v1.6.11

- rancher/v1.6/en/api/v2-beta/access-control/index.md
> Adding ActiveDirectory to list of providers served by auth-service

- rancher/v1.6/en/kubernetes/ingress/index.md
docs for https://github.com/rancher/rancher/issues/10102
@deniseschannon
> docs for adding ingress healthchecks

- rancher/v1.6/en/faqs/agents/index.md
Fixes https://github.com/rancher/rancher/issues/10371
> Add FAQ on localhost reference in resolv.conf

- rancher/v1.6/en/faqs/server/index.md
- rancher/v1.6/en/installing-rancher/installing-server/index.md
https://github.com/rancher/rancher/issues/8370
> Add info on configuring database proxy timeout parameters

- rancher/v1.6/en/environments/registries/ecr_updater.md
- rancher/v1.6/en/environments/registries/index.md
- rancher/v1.6/en/windows/index.md
https://github.com/rancher/rancher/issues/10329
> Description how to use ECR updater in a Windows environment

- rancher/v1.6/zh/configuration/access-control/index.md
update Active Directory translation.
> update AD translation

- rancher/v1.6/en/upgrading/index.md
> Fix typo in upgrade manager setting value bullets

- rancher/v1.6/en/cattle/containers/index.md
fixed link to scheduling docs page
> fixed link to scheduling docs page

- os/v1.1/en/storage/additional-mounts/index.md
https://github.com/rancher/os/issues/2238
> The 4th parameter is mandatory for ros cli

- os/v1.2/en/system-services/environment/index.md
https://github.com/rancher/os/issues/1873
> Support for updating PATH variables

- os/v1.2/en/running-rancheros/server/install-to-disk/index.md
https://github.com/rancher/os/issues/2155
> Support URL when using ros install -c

- os/v1.2/en/system-services/system-docker-volumes/index.md
https://github.com/rancher/os/issues/2188
> Persisting user volumes

- os/v1.2/en/configuration/adding-kernel-parameters/index.md
https://github.com/rancher/os/issues/1870
> Add ability to configure docker-sys bridge

- rancher/v2.0/en/quick-start-guide/index.md
Removing the extra space in the bullet as it causes the content to be displayed incorrectly
> Fixing the indentation as it causes display issues

- os/v1.2/en/running-rancheros/server/raspberry-pi/index.md
https://github.com/rancher/os/issues/2280
> Remove Raspberry Pi 2

- _includes/rancher-sidebar-v2.0.html
> adding faq to navbar.

- rancher/v2.0/en/quick-start-guide/index.md
Updated the port requirements per the [matrix](https://github.com/rancher/rke/issues/212#issuecomment-356566698) that @galal-hussein sent me. Also added Canal to the matrix (ports 80 and 443).
> Port requirements

- os/v1.x/en/configuration/images-prefix/index.md
https://github.com/rancher/os/issues/2178
> Config ROS image prefix for install and all rancher/os services

- os/v1.x/en/configuration/ssh-settings/index.md
https://github.com/rancher/os/issues/1039
> Configure ssh port and IP

- os/v1.x/en/configuration/adding-kernel-parameters/index.md
https://github.com/rancher/os/issues/1785
> Auto reboot after a kernel panic

- rancher/v1.6/en/kubernetes/providers/index.md
https://github.com/rancher/rancher/issues/12713
> Describe how to configure clusterid when using k8s

- rancher/v1.6/en/cli/commands/index.md
https://github.com/rancher/rancher/issues/13781
> update for --format info

- rancher/v1.6/zh/environments/index.md
> Fix small typos

- rancher/v1.6/en/hosts/index.md
This is for v1.6.19 where we validated Ubuntu 18.04
> Add note for local caching nameserver (Ubuntu 18.04)

- os/v1.1/en/boot-process/logging/index.md
I guess acpid is what you meant.
> Typofix: acipd to acpid

- rancher/v1.6/en/environments/certificates/index.md
fix formatting for **Read from File**
> fix formatting

- rancher/v1.6/en/upgrading/index.md
This PR addresses this issue https://github.com/rancher/docs/issues/1158
> Add note for upgrading Rancher 1.6 HA clusters
