rancher/rancher.github.io

rancher/faqs/troubleshooting/index.md

Filename used underscore instead of hyphen.

Fix cattle debug log filename

---

rancher/installing-rancher/installing-server/multi-nodes/index.md

Instead of maintaining independent Docker images for the services
we are going to use rancher/server. The binaries are already inside
the container because they run there as a self contained unit.

Updated docs to run multiple binaries out of rancher/server

---

rancher/rancher-ui/applications/stacks/adding-service-alias/index.md
rancher/rancher-ui/applications/stacks/index.md

The scenario had an error where it stated that AppV2 can be removed after testing and thus result in the service being upgraded. That's incorrect and should ready AppV1 otherwise, you haven't upgraded anything.

Fixes an error in the scenario example

---

rancher/rancher-ui/applications/stacks/adding-balancers/index.md

Added an example on the load balancer with SSL Termination based on what I understood after trying it out to make the text clearer.
Also added data on multiple certificates which wasn't covered.
Question - what's your "policy" regarding screenshots in the docs? I don't see any right now and I think it could make the text way easier to understand as some long winded sentences could simply refer to a picture below.

Adds an example to give more understanding to the reader.

---

os/quick-start-guide/index.md

The code snippet at section "Deploying a system service container" of
<http://docs.rancher.com/os/quick-start-guide/> contains an error:
```
[rancher@rancher-01 ~]$ sudo echo "sudo system-docker start busydash" >>/opt/rancher/bin/start.sh
-bash: /opt/rancher/bin/start.sh: Permission denied
```
The correct command is the following:
```
[rancher@rancher-01 ~]$ echo "sudo system-docker start busydash" | sudo tee -a /opt/rancher/bin/start.sh
sudo system-docker start busydash
[rancher@rancher-01 ~]$
```
Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>

os/quick-start-guide: Fix code in example

---

rancher/rancher-services/storage-service/index.md

Currently the docs specify the label convoy.gluster = true, which doesn't work using the stack from the catalog.  This commit modifies the docs to use the default host label as per https://github.com/rancher/rancher-catalog/blob/master/templates/convoy-gluster/0/rancher-compose.yml.

Updates rancher-services/storage-services with  the host label convoy.glusterfs=true

---

rancher/latest/en/catalog/index.md

Noticed that the Markdown for the config.yml example was rendering in likely unsatisfactory way so made some adjustments to get it to render correctly...at least that is true with Chrome and the Markdown Preview plugin.

fix some Markdown fence + indent silliness

---

rancher/latest/en/rancher-services/internal-dns-service/index.md

It seems that the names of containers are `<stack_name>_<service_name>_<number>`

change <environment_name> to <stack_name>

---

os/running-rancheros/cloud/gce/index.md

Not sure whether that's because the gce image is not built anymore or if the regular tar ball works?

There is no gce in the artifact name

---

os/rancheros-tools/ros/config/index.md

`images` is a helper used during the build process and doesn't really need to be in the docs
`import` will be removed in v0.5

Remove images and import subcommands from ros config

---

rancher/latest/en/rancher-services/internal-dns-service/index.md

Example demonstrates using `bar.stackb` but the actual text described using `foo.stackb`.
The casing changes too (e.g. `stackB`) but if my understanding is correct then DNS is case insensitive so it should not matter. Let me know if I am wrong (or if you would just like me to) and I can correct that in the example too.

Corrected typo in Internal DNS Service page

---

rancher/latest/en/catalog/private-catalog/index.md

This looks better IMO. But some may not agree.
Please look at the parsed Markdown, not just the MD itself.

Set the types as a unordered list

---

rancher/v1.2/en/configuration/settings/index.md

The current link in the docs returns a 404 error because of the word "catalogs" instead of "catalog" in the link itself.

Fix private catalog doc link

---

rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/index.md

I couldn't get Kubernete's kubectl exec to work with Rancher 1.2.0-pre2 because I had nginx providing ssl termination as per the instructions here. I changed the Connection header to "Upgrade" and kubectl works. Looks like kubectl or whatever library it's using is case-sensitive.

kubectl's exec requires upgrade to be Capitalised

---

rancher/v1.2/en/cattle/rancher-compose/commands/index.md

Fixes small typo on [rancher-compose commands](http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/commands/) page. Changes "scale of servives" to "scale of services".

Fix typo in rancher-compose docs: servives => services

---

rancher/v1.2/en/quick-start-guide/index.md

Was https://docs.docker.com/installation/ubuntulinux/ - changed to https://docs.docker.com/engine/installation/linux/ubuntulinux/

Fix moved URL for Docker installation on Ubuntu

---

os/running-rancheros/server/pxe/index.md

`formatzero` and quotes around URL no longer required.
Waiting for v0.7.0

Update PXE docs

---

rancher/v1.2/en/quick-start-guide/index.md

The existing docker install page link is broken. The new link is 
https://docs.docker.com/engine/installation/linux/ubuntulinux/

fixed docker installation link for ubuntu linux

---

rancher/v1.2/en/faqs/troubleshooting/index.md

The header 'Running Ubuntu, and containers are unable to communicate with each other.' won't appear as a header unless there is whitespace before the `####`.

Fix whitespace needed for Ubuntu header

---

os/quick-start-guide/index.md

Should be the same as http://docs.rancher.com/os/configuration/#getting-values, right?

fix config key for dns

---

rancher/v1.2/en/quick-start-guide/index.md

Otherwise it gives FATA[0000] flag provided but not defined: -s

Fix typo for Rancher CLI command

---

rancher/v1.4/en/cattle/webhook-service/index.md

got some extra br tags that don't seem to do anything.
looks like the message text should be 70% instead of 10%

Fix typos on webhooks page

---

rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/index.md

Added headers to HAProxy configuration to tell Rancher that it's behind a proxy that's handling SSL.

add SSL headers for haproxy

---

rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/index.md

Current HAProxy example will not work, and HAProxy will complain with these errors:
[WARNING] 354/020838 (6) : config : 'option forwardfor' ignored for frontend 'http-in' as it requires HTTP mode.
[WARNING] 354/020838 (6) : config : 'option forwardfor' ignored for backend 'rancher_servers' as it requires HTTP mode.
Solution, change `mode tcp` to  `mode http`. `mode http` is usually used for HTTP/S traffic, according to https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4

HAProxy needs `mode http` not `mode tcp` 

---

rancher/v1.5/en/installing-rancher/installing-server/index.md

Duplicate entries for Running Rancher Server Behind an Application Load Balancer (ALB) in AWS section so I removed one.

Duplicate entries for  Application Load Balancer section

---

rancher/v1.5/en/cattle/adding-load-balancers/index.md

This took me some time and is nowhere in the documentation. Lower number in the priority field means higher priority in the load balancer.

Make rancher-compose priority clearer

---

rancher/v1.5/en/cli/index.md

Several instances of "account API keys" or "environment API key" point to non-existing pages. Fixing by adding "v2-beta" back into the URL.

Fix 404 for "account API keys" and "environment API key"

---

rancher/v1.5/en/cattle/internal-dns-service/index.md

There was a mistake, suggesting to use underscore to construct the unique container name from the stack, service and number.
This should be changed to **-**.

Fixing documentation for ping by container name.

---

rancher/v1.5/en/hosts/index.md

All of the Docker installation commands turned `| sh` into `\| sh`. I've removed the backslash.

remove backslash from command pipe

---

_includes/rancher-sidebar-v1.6.html
rancher/v1.6/en/cattle/volumes/index.md

This document describe how to use volumes within cattle. It covers
different volume scopes, volume management with Rancher CLI, and
explains the difference between v2 and v1 compose.

Document volume usage in cattle

---

rancher/v1.1/en/cattle/external-dns-service/index.md
rancher/v1.2/en/cattle/external-dns-service/index.md
rancher/v1.3/en/cattle/external-dns-service/index.md
rancher/v1.4/en/cattle/external-dns-service/index.md
rancher/v1.5/en/cattle/external-dns-service/index.md
rancher/v1.6/en/cattle/external-dns-service/index.md

IAM role attached to instances only possible v1.5 and higher
Follow-up on https://github.com/rancher/rancher.github.io/pull/716

Add IAM role requirements for route53 external DNS provider

---

rancher/v1.1/en/cattle/health-checks/index.md
rancher/v1.2/en/cattle/health-checks/index.md
rancher/v1.3/en/cattle/health-checks/index.md
rancher/v1.4/en/cattle/health-checks/index.md
rancher/v1.5/en/cattle/health-checks/index.md
rancher/v1.6/en/cattle/health-checks/index.md

Updated `navigatiing` => `navigating` in all the versions
https://github.com/rancher/rancher.github.io/search?utf8=%E2%9C%93&q=navigatiing&type=

Fix typo in health-check index.md doc

---

_includes/rancher-sidebar-v1.6.html

From 'Roles in an Environments' to 'Roles in an Environment'.

corrected plural to singular for Environment

---

rancher/v1.6/en/kubernetes/disaster-recovery/index.md

where it said, "stop immediately" is confusing. The reader might think, "stop what?" best to reassure that the etcd cluster is healthy.

modified "healthy scenario" behavior.

---

os/v1.0/en/configuration/index.md

This [sysctl setting] link was generating a 404 error. I removed the index.md file from the link. It also appeared that index.html was ok to use, but I went with removing it instead.

Changed link [sysctl setting] to one that works

---

rancher/v1.6/en/kubernetes/backups/index.md

'mount a network storage' seems to be missing a noun whereas 'mount network storage' for some reason seems proper.

Removed the 'a'

---

_includes/rancher-sidebar-v2.0.html

There's an extra " that shows up in the side bar of the Rancher website. This PR removes it.

Remove errant "

---

rancher/v1.0/en/installing-rancher/installing-server/no-internet-access/index.md
rancher/v1.0/en/upgrading/index.md

The following links should be valid, but present "403" error pages.
- http://rancher.com/docs/rancher/v1.0/en/upgrading/
- http://rancher.com/docs/rancher/v1.0/en/installing-rancher/installing-server/no-internet-access/
My suspicion is that the Jekyll YAML front matter has been corrupted with a rogue character, and this is preventing the page from being displayed.
I'm afraid this commit is un-tested, as I've not looked into what is required for verification.

Fix documentation pages displaying "403 Forbidden"

---

os/v1.1/en/quick-start-guide/index.md

Smart quotes are evil, and mess up command lines

Got rid of smart quotes in the busydash example

---

rancher/v1.6/en/rancher-services/storage-service/rancher-ebs/index.md

https://github.com/rancher/rancher/issues/9633

kmsKeyId is optional since v0.8.8 when using encrypted EBS volumes

---

rancher/v1.6/en/cli/commands/index.md

I came straight to this entry in the docs and was confused not to find more information about arguments that could be passed to the wait sub-command. Then I saw that it is designed to work with the global options mentioned earlier in the page.

Add reference to the waiting for resources section

---

rancher/v1.6/en/hosts/index.md

- Add 1.13, 17.03 as supported for k8s 1.8
- Add 17.09 as supported + download link
- Add 17.10 as unsupported + download link

Updated Docker (supported) versions

---

os/v1.1/en/storage/using-zfs/index.md

The majority of this doc uses `zpool1` as the example pool, with the exception of the `zdb` commands. Should the `zdb` example benefit from using the same `zpool1` instead of the current `zpool_1` to reduce confusion?

Unify zpool1 example with previous instructions

---

_includes/os-sidebar-v1.0.html

This may make the users confused,  all of 1.x is LTS.

Remove 1.0 LTS

---

rancher/v2.0/en/quick-start-guide/index.md

Added section for deploying Rancher on Ubuntu Kubernetes Clusters. Link is included to upstream kubernetes manual provided by Google: [https://kubernetes.io/docs/getting-started-guides/ubuntu/rancher/](https://kubernetes.io/docs/getting-started-guides/ubuntu/rancher/)

Added section for deploying Rancher on Ubuntu Kubernetes Clusters. 

---

os/v1.2/en/configuration/index.md

Link in page:
http://rancher.com/docs/os/v1.2/en/configuration/
for the __sysctl settings__ goes to:
http://rancher.com/docs/os/v1.2/en/sysctl/
which is an http 404
I think it should go to:
http://rancher.com/docs/os/v1.2/en/configuration/sysctl/
I have simply added the __configuration__ missing bit to the index.md link, but I have not tested it.

sysctl link in os/v1.2/en/configuration/index.md fix

---

rancher/v1.6/en/hosts/index.md

Due to [bug in rancher 1.6.14](https://github.com/rancher/rancher/issues/10970) minimal version for `docker 17.12.x` is `1.6.15`

Update minimal rancher server version for docker 17.12

---

rancher/v1.6/en/installing-rancher/installing-server/index.md

Replace with reference to the presumably-correct configuration setting (as of MySQL 5.7) that the document refers to.

Remove reference to max_packet_size

---

rancher/v1.6/en/hosts/index.md

Added explanation that a x86 architecture is required to run a Rancher node

Reflect x86 architecture requirement

---

rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/index.md

To avoid warnings when running Nginx you have to use http2 module instead of spdy.
From official doc http://nginx.org/en/docs/http/ngx_http_spdy_module.html
Module ngx_http_spdy_module: This module was superseded by the ngx_http_v2_module module in 1.9.5.

Use http2 module in Nginx config instead of spdy

---

rancher/v1.6/en/cattle/secrets/index.md

A note to users mentioning about docker compose + secrets combination wont work for building stacks. need to use rancher cli for this.

Note to users about rancher compose + secrets combination

---

os/v1.1/en/configuration/adding-kernel-parameters/index.md

The kernel argument is rancher.autologin not rancheros.autologin.

Fix autologin typo

---

rancher/v1.2/en/installing-rancher/installing-server/index.md
rancher/v1.3/en/installing-rancher/installing-server/index.md
rancher/v1.4/en/installing-rancher/installing-server/index.md
rancher/v1.5/en/installing-rancher/installing-server/index.md
rancher/v1.6/en/installing-rancher/installing-server/index.md
rancher/v1.6/zh/installing-rancher/installing-server/index.md

ContentKing (SEO tool) crawls links on pages and when these links with double slashes are found they are considered a separate page. As the (correct) page with single slash in its path already exists, this page will cause issues with various metrics (e.g. duplicate title).

Fix links with double slashes in path

---

_includes/os-header.html

Per feedback from the web team, the site's SEO score needs to be improved. The lack of a Twitter card is affecting the score.

Add Twitter card to header

---

_includes/os-header.html

Per feedback from the web team, the site's SEO score needs to be improved. The lack of Open Graph meta tags is affecting the score.

Add Open Graph tags to header

---

Dockerfile.build

Builds have been failed on `Step 10/14 : RUN jekyll build` since PR #1080. From the [build logs](https://drone-publish.rancher.io/rancher/rancher.github.io/16/1/3) the error is
> There was an error while trying to write to `/build/Gemfile.lock`. It is likely that you need to grant write permissions for that path. The command '/bin/sh -c jekyll build' returned a non-zero code: 23 time="2020-01-30T22:00:29Z" level=fatal msg="exit status 23"

Test adding chown - builds have failed since #1080
